# Generated by Django 3.0.5 on 2020-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='images/')),
                ('pl', models.IntegerField()),
                ('ps', models.IntegerField()),
                ('top', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SicPizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='images/')),
                ('pl', models.IntegerField()),
                ('ps', models.IntegerField()),
                ('top', models.IntegerField()),
            ],
        ),
    ]
