# Generated by Django 3.0.5 on 2020-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='pl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='ps',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicpizzas',
            name='pl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicpizzas',
            name='ps',
            field=models.FloatField(),
        ),
    ]
